Documenter 1.0 upgrade
SciML/DiffEqDocs.jl pull request #697
Opened 2023-09-30 04:50 UTC by ArnoStrouwen

2023-09-30 04:53 UTC, ArnoStrouwen commented
SDE example is only compatible with SciMLBase 2.
But not all other dependencies have been upgraded to version 2 yet.
BoundaryValueDiffEq, specifically.

There is also another error regarding a solver name that I don't know how to fix: GeneralMIRK4

2023-09-30 05:02 UTC, ArnoStrouwen commented
Finally found the setting to get the buildkite working on PR.

2023-09-30 11:41 UTC, ChrisRackauckas commented
https://github.com/SciML/BoundaryValueDiffEq.jl/pull/109 should be the only one left, and I hope it merges today.

2023-10-01 15:57 UTC, ChrisRackauckas commented on docs/src/tutorials/bvp_example.md
> +function bc2!((resid_a, resid_b), (u_a, u_b), p, t) # u[1] is the beginning of the time span, and u[end] is the ending
@avik-pal is this not right?

2023-10-01 22:24 UTC, avik-pal commented on docs/src/tutorials/bvp_example.md
> +function bc2!((resid_a, resid_b), (u_a, u_b), p, t) # u[1] is the beginning of the time span, and u[end] is the ending
The `t` should not be present

2023-10-01 22:26 UTC, avik-pal requested changes

2023-10-01 22:26 UTC, avik-pal commented on docs/src/tutorials/bvp_example.md
> +function bc2!((resid_a, resid_b), (u_a, u_b), p, t) # u[1] is the beginning of the time span, and u[end] is the ending
```suggestion
function bc2!((resid_a, resid_b), (u_a, u_b), p) # u[1] is the beginning of the time span, and u[end] is the ending
```

2023-10-01 23:55 UTC, ChrisRackauckas commented
Looks like there's still more. @avik-pal can you complete this? Let's make sure that the constructors are "complete" before being set in stone.

2023-10-07 09:59 UTC, ChrisRackauckas commented on docs/Project.toml
> +BoundaryValueDiffEq = "5"
```suggestion
BoundaryValueDiffEq = "5.1"
```

2023-10-07 10:58 UTC, ChrisRackauckas commented on docs/src/tutorials/bvp_example.md
> +function bc2b!(resid_a, u_b, p) # u_b is at the ending of the time span
```suggestion
function bc2b!(resid_b, u_b, p) # u_b is at the ending of the time span
```

2023-10-07 18:30 UTC, merged